name: Build Application Job

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest  # Use the Ubuntu runner
    steps:
      # Step 1: Checkout Code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0  # Specify the .NET version (replace with your version)

      # Step 3: Restore Dependencies
      - name: Restore dependencies
        run: dotnet restore path/to/solution.sln  # Replace with the path to your .sln file

      # Step 4: Build
      - name: Build solution
        run: dotnet build path/to/solution.sln --configuration Release --no-restore

      # Step 5: Run Tests (Optional)
      - name: Run tests
        run: dotnet test path/to/solution.sln --no-build --verbosity normal
