name: New Threat workflow

on:
  workflow_call:
    secrets:
      DTRACK_PROJECT_KEY:
        required: true
      DTRACK_API_KEY:
        required: true
    inputs:
      cveNumber:
        description: 'CVE to test for'
        required: false
        default: 'null'
        type: string
      vulnerablePackage:
        description: 'Packages affected by CVE'
        required: true
        default: 'null'
        type: string
      packageVersions:
        description: 'Versions affected by CVE'
        required: true
        default: 'null'
        type: string

jobs:
  scan-for-cve:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download SBOM Artifact
        env:
          DTRACK_PROJECT_KEY: ${{ secrets.DTRACK_PROJECT_KEY }}
          DTRACK_API_KEY: ${{ secrets.DTRACK_API_KEY }}
        run: |
          curl "http://localhost:8081/api/v1/component/project/$DTRACK_PROJECT_KEY" \
            -H "X-Api-Key: $DTRACK_API_KEY" \
            -H "Content-Type: application/json" -o sbom.json -vv


      - name: Install jq
        run: sudo apt-get install jq

      - name: Check for Specific Package Version
        run: |
          PACKAGE_NAME=${{ github.event.inputs.vulnerablePackage }} 
          PACKAGE_VERSION=${{ github.event.inputs.packageVersions }} 

          if jq -e ".components[] | select(.name == \"$PACKAGE_NAME\" and .version == \"$PACKAGE_VERSION\")" sbom.json > /dev/null; then
            echo "Package $PACKAGE_NAME version $PACKAGE_VERSION is present in the SBOM."
          else
            echo "Package $PACKAGE_NAME version $PACKAGE_VERSION is NOT present in the SBOM."
            exit 1
          fi
