name: Secure Deployment

on: 
  workflow_call:
    secrets:
      GITHUB_TOKEN:
        required: true

jobs:
  owasp-zap-scan:
    uses: DPaaS-organization/DPaaS-Admin-Repo/.github/workflows/owasp-zap.yaml@main
    secrets: 
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  secure-deployment:
   uses: DPaaS-organization/DPaaS-Admin-Repo/.github/workflows/secure-deployment.yaml@main 
