name: Secure Deployment

on: 
  workflow_call:
    secrets:
      GITHUB_REPOSOTIRY_TOKEN:
        required: true
      PRODUCTION_HOST_URL:
        required: true
      DB_USER:
        required: true
      DB_PASSWORD:
        required: true
      DB_HOST_URL:
        required: true
jobs:
  owasp-zap-scan:
    uses: DPaaS-organization/DPaaS-Admin-Repo/.github/workflows/owasp-zap.yaml@main
    secrets: 
      GITHUB_REPOSOTIRY_TOKEN: ${{ secrets.GITHUB_REPOSOTIRY_TOKEN }}
  secure-deployment:
   uses: DPaaS-organization/DPaaS-Admin-Repo/.github/workflows/secure-deployment.yaml@main 
