name: Secure Deployment

on: 
  workflow_call:
    secrets:
      ADMIN_ACCESS_TOKEN:
        required: true
      PRODUCTION_HOST_URL:
        required: true
      DB_USER:
        required: true
      DB_PASSWORD:
        required: true
      DB_HOST_URL:
        required: true
jobs:
  owasp-zap-scan:
    uses: DPaaS-organization/DPaaS-Admin-Repo/.github/workflows/owasp-zap.yaml@main
    secrets: 
      ADMIN_ACCESS_TOKEN: ${{ secrets.ADMIN_ACCESS_TOKEN }}
  secure-deployment:
    uses: DPaaS-organization/DPaaS-Admin-Repo/.github/workflows/deploy-application.yaml@main 
    needs: owasp-zap-scan
    secrets:
      PRODUCTION_HOST_URL: ${{ secrets.PRODUCTION_HOST_URL }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST_URL: ${{ secrets.DB_HOST_URL }}
