name: Secure Deployment

on: 
  workflow_call:
    secrets:
      PRODUCTION_HOST_URL:
        required: true
      DB_USER:
        required: true
      DB_PASSWORD:
        required: true
      DB_HOST_URL:
        required: true
    inputs:
      dockerImageName:
        required: true
        type: string
jobs:
  deploy-to-test:
    uses: DPaaS-organization/DPaaS-Admin-Repo/.github/workflows/deploy-to-test.yaml@main
    with:
      ${{ inputs.dockerImageName }}
  owasp-zap-scan:
    uses: DPaaS-organization/DPaaS-Admin-Repo/.github/workflows/owasp-zap.yaml@main
  secure-deployment:
    uses: DPaaS-organization/DPaaS-Admin-Repo/.github/workflows/deploy-application.yaml@main 
    needs: owasp-zap-scan
    secrets:
      PRODUCTION_HOST_URL: ${{ secrets.PRODUCTION_HOST_URL }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST_URL: ${{ secrets.DB_HOST_URL }}
